name: Keep Render App Alive

on:
  schedule:
    - cron: '*/10 6-23,0 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Application
        run: |
          echo "Sending ping at $(date)"
          curl -s -o /dev/null -w "%{http_code}" https://caraid-api-node.onrender.com/ping
          echo "Ping completed"